#!/bin/sh
set -e -x

export REPO_DIR=$( cd $(dirname "`dirname $0`") && pwd )
if [ -z "$PYTHON_VIRTUALENV" ]; then
    export PYTHON_VIRTUALENV=".test-venv-`uname -s`-`uname -m`"
fi
export VIRTUAL_ENV_DIR="$REPO_DIR/$PYTHON_VIRTUALENV"
python -m venv $PYTHON_VIRTUALENV
echo "Using virtualenv located in : $VIRTUAL_ENV_DIR"
. "$VIRTUAL_ENV_DIR/bin/activate"
pip install -q -r $REPO_DIR/requirements-test.txt

cd $REPO_DIR
export PYTHONPATH=".:`pwd`"

echo "==> Static Code Analysis for PEP8 style guide and various errors"
flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
echo "==> Full flake8 style check"
flake8 --config=setup.cfg --statistics --count .
echo "==> Executing tests with code coverage collection"
pytest --cov=project --cov-report=html --cov-report=term-missing tests/

